FROM golang:1.25-alpine
RUN apk add --no-cache ca-certificates
RUN go install github.com/air-verse/air@latest
ENV PATH="/go/bin:$PATH"

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]
